#!/usr/bin/env python
# usage: export PYTHONSTARTUP="$HOME/.pythonrc"

import os
import readline
import rlcompleter

# Restore our command-line history, and save it when Python exits.
historyPath = os.path.expanduser("~/.python_history")
# Create a blank history file if it doesn't exist already
if not os.path.exists(historyPath) and not os.path.isdir(historyPath):
    try:
        open(historyPath, 'w').close()
    except IOError:
        pass

if os.access(historyPath, os.W_OK):
    import atexit
    atexit.register(lambda x=historyPath: readline.write_history_file(x))
    del atexit
if os.access(historyPath, os.R_OK):
    readline.read_history_file(historyPath)

readline.parse_and_bind("tab: complete")
readline.set_history_length(100000)
del rlcompleter, historyPath

from pprint import pprint as pp
