#!/bin/bash
set -e

# Drop into '$dstrcdir' whatever you want transported to the remote server,
# once there, use the 'sshrc' script to customize startup.
# WARNING: bash cmdline length can only be so big, data has to fit there.
packenv() {
  local TMPRCDIR="$1"
  local dstrcdir="/tmp/$TMPRCDIR"
  mkdir -p "$dstrcdir"
  # setup bash remote environment
  cat ~/Source/dotfiles/bashrc |
    sed "s!~/Source/shlibs/!${dstrcdir}/!" > "$dstrcdir/bashrc"
  cp ~/Source/dotfiles/inputrc "$dstrcdir/inputrc"
  cat ~/Source/dotfiles/tmux.conf |
    sed "s!default-command ''!default-command 'bash --rcfile $dstrcdir/sshrc'!" \
    > "$dstrcdir/tmux.conf"
  cp ~/Source/shlibs/*.lib.sh "$dstrcdir/" &>/dev/null
  # setup gdb
  cat ~/Source/dotfiles/gdbinit |
    sed "s!~/Source/dotfiles/!${dstrcdir}/!" > "$dstrcdir/gdbinit"
  cp ~/Source/dotfiles/stl-views.gdb "$dstrcdir/stl-views.gdb"
  # adjust vim files for remote environemnt
  mkdir -p "$dstrcdir/vimfiles"
  cat ~/Source/dotfiles/vimrc |
    sed -e "s!~/Source/dotfiles/!${dstrcdir}/!" \
        -e "s!~/.vimfiles!${dstrcdir}/vimfiles!" \
    > "$dstrcdir/vimrc"
  # copy some binaries
  mkdir -p "$dstrcdir/bin"
  cp ~/Source/shlibs/csv2d \
     ~/Source/shlibs/d2fw \
     ~/Source/shlibs/l2f \
     ~/Source/shlibs/crush \
  "$dstrcdir/bin/"
  # remote startup script
  cat > "$dstrcdir/sshrc" <<-EOF
		HOSTPROMPT=1 source '$dstrcdir/bashrc'
		export PATH="$dstrcdir/bin:\$PATH"
		bind -f '$dstrcdir/inputrc'
		alias vim='vim -u $dstrcdir/vimrc'
		alias gdb='gdb -x $dstrcdir/gdbinit'
		alias bp='nc $(hostname) ${PIPEPORT:-27284}'
		tux() { TERM=screen-256color tmux -2u -f "$dstrcdir/tmux.conf" new-session -AD -s "\$(hostname)"; }
		# only cleanup if not inside tmux
		trap "[ \$TMUX ] || rm -rf '/tmp/$TMPRCDIR'; exit" 0
EOF
  cd /tmp/ && tar cJf - "$TMPRCDIR" | base64 &&
    rm -rf "$dstrcdir"
}

sshrc() {
  local TMPRCDIR="$(mktemp -ud "${USER}rc.XXXXXX")"
  ssh -t "$@" "
    echo '$(packenv "$TMPRCDIR")' | base64 -d | tar xJf - -C /tmp
    exec bash --rcfile '/tmp/$TMPRCDIR/sshrc'"
}

sshrc "$@"
